server:
  #启动端口
  port: 8080
  servlet:
    #启动路径
    context-path: /oldBook

spring:
    #数据库连接及数据库连接池配置
    datasource:
        #数据库连接驱动
        driver-class-name: com.mysql.jdbc.Driver
        #数据库连接地址
        url: jdbc:mysql://127.0.0.1:3306/old_book
        #用户名
        username: root
        #密码
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#  热加载配置
    devtools:
        restart:
          #设置启动热加载
          enabled: true
          #扫描变化的类的路径
          additional-paths: src/main/java
# 使用thymeleaf模板
    thymeleaf:
      enabled: true
      #模板前缀
      prefix: classpath:/templates/
      #模板后缀
      suffix: .html
      #模型  默认HTML5
      mode: HTML5
      #缓存设置为false 实时观察变化
      cache: false
      #编码格式
      encoding: utf-8


mybatis:
  mapper-locations: classpath:mapping/*.xml


